# Generated by Django 4.2.2 on 2023-06-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feeding_date_toy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='finches',
        ),
        migrations.AddField(
            model_name='finch',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
